### ISSUE TITLE
How is the DNS over HTTPS better than just using Google DNS?

### ISSUE THREAD

**Issue by NightMachinary** [SadeghHayeri/GreenTunnel#1]
(I’m a total noob so :) )
فارسی هم اوکیه😅🖖🏼

**Comment by SadeghHayeri** [comment]
Hi
some ISPs inject DNS records on every query like requests!
for example, set your DNS server to 3.3.3.3 (this is not a real DNS server) and query 'youtube.com', see? it response with 10.10.34.35, that response comes from ISP!
so I decide to use DoH and DoT in GreenTunnel.

with my ISPs google DNS server dose not work too, to check this you can run `dig +short @8.8.8.8 youtube.com AA` and see 10.10.34.35 again.
