### ISSUE TITLE
Doesn't work in Russia

### ISSUE THREAD

**Issue by AlexMak58** [SadeghHayeri/GreenTunnel#10]
**Describe the bug**
Unfortunately, doesn't work in Russia.

**To Reproduce**
To be in Russia with [MTS](https://en.wikipedia.org/wiki/MTS_(network_provider)) provider and standard DNS from the ISP.

**Expected behavior**
Doesn't work on sites blocked by the ISP.

**Screenshots**
![MTC](https://user-images.githubusercontent.com/34411074/57186611-e4f51d00-6ed1-11e9-9d00-7d9079a1e95f.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux x64 KDE Plasma 5
 - Browser: Firefox
 - Version: 66.0.3 x64
 - GUI: w/o
 - NodeJS: 11.14.0
 - NPM: 6.9.0
 - Installation method: root with flag -g (npm -g)

**Comment by AlexSysadmin** [comment]
@AlexMak58  you can query your desired website using  " dig " and check the returned DNS lookup response too see if it is the correct response or is it just some random internal IP from your ISP  ,or  you could use an encrypted DNS provider  or DoH , DNS over HTTPS in the first place  .

**Comment by AlexMak58** [comment]
@AlexSysadmin I did not quite understand what should end up. Should I get my ISP DNS address?

**Comment by AlexSysadmin** [comment]
@AlexMak58 No , if you are using linux 
just run this command : dig  google.com
replace google with the website you are trying to visit , like 
dig  facebook.com

and see if the response you get is a valid IP address , 
next try using a public DNS server like google , and run the query again ,.using this command 
dig @8.8.8.8 facebook.com 
or any website you are trying to visit and is filtered , compare their responses , and paste the dig results here .

**Comment by AlexMak58** [comment]
A similar problem: #37
