### ISSUE TITLE
Can't connect to the internet without Green Tunnel on

### ISSUE THREAD

**Issue by Alnura13** [SadeghHayeri/GreenTunnel#117]
I know nothing about coding and stuffs, I just wanted to open some restricted website so I tried green tunnel.
I went and download the latest windows version, unrar the file, and then run the installer inside the folder.
After the installer is done, I got something that says green tunnel is off and so I press the button to turn it on.
After pressing it once, it for some reason ask me what program to open some file in which I didn't choose any program.
The thing still says that green tunnel is off but when I try it, I can open the restricted websites.
Then after browsing for a while, I decided to turn off green tunnel.
When I turn off green tunnel though, for some reason I can't open anything in the internet, saying that there's no connection.
When I turn it on again, everything is working fine.
I tried uninstalling it (I mean deleting the folder the program was in) but I still can't use the internet.
Can anyone help me with this problem? I just want everything back to normal.

**Comment by Alnura13** [comment]
I can fix it somewhat by disabling proxy server but is there any other way?

**Comment by myusufid** [comment]
have the exactly same problem, please help

**Comment by Alnura13** [comment]
I "fixed" it by turning off my laptop's firewall
