### ISSUE TITLE
Mac GUI App didn't work

### ISSUE THREAD

**Issue by emranovin** [SadeghHayeri/GreenTunnel#12]
**Describe the bug**
I can not use gui app (Even in v1.3.2 version)

**Desktop (please complete the following information):**
 - OS:  [macOS Mojave]
 - Version [10.14.4]

**Comment by AptimiCt** [comment]
Good evening. You may want to check your system settings on the security tab and confirm that you want to run the application.

**Comment by emranovin** [comment]
> Good evening. You may want to check your system settings on the security tab and confirm that you want to run the application.

I can run the app. but it doesn't bypass the filtering when it turns to green. 
This problem happened to all of my friends. CLI works just fine but not the GUI.

**Comment by pramuditorh** [comment]
Yes, I have the same problem. It shows that the button is green but cannot bypass the DPI.

**Comment by SadeghHayeri** [comment]
Should be fully resolved by new release (v1.6.7).
