### ISSUE TITLE
GoodByeDPI

### ISSUE THREAD

**Issue by stokito** [SadeghHayeri/GreenTunnel#13]
https://github.com/ValdikSS/GoodbyeDPI
This project looks similar to your and mostly intended for Russia and Ukraine. Can you tell a difference with GreenTunnel ? If this projects are similar maybe you can merge them or at least mention in README as alternative/competitor.
Thank you

**Comment by stokito** [comment]
Oh I see, this is port of GoodByeDpi for nodejs

**Comment by SadeghHayeri** [comment]
Yes this is like a port of GoodByeDpi for NodeJS, also GreenTunnel works on layer7 and uses http-proxy to change system traffic (this make GreenTunnel OS independent)
