### ISSUE TITLE
macOS(Darwin) System Proxy

### ISSUE THREAD

**Issue by pcr910303** [SadeghHayeri/GreenTunnel#14]
**Describe the bug**
System Proxy is not enabled when activated GreenTunnel CLI

**To Reproduce**
```
$ gt
```

**Expected behavior**
gt doesn't work at all.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: Safari 12.1.1

**Additional context**
1. System Proxy is not enabled automatically on CLI start.
```diff
// bin/gt.js#L107
-	await proxy.start();
+	await proxy.start(true);
```
2. In High Sierra, (I'm not sure about Mojave), the commands to activate system proxy is wrong.
```shell
sh -c "$(node --eval "console.log('networksetup -listnetworkserviceorder | grep \'Wi-Fi\' -B 1 | cut -d\')\' -f2')")"
# => denotes that a network service is disabled.
# => Wi-Fi
```
```diff
// src/utils/system-proxy.js#L16 and #L22
-	const wifiAdaptor = (await exec('networksetup -listnetworkserviceorder | grep \'Wi-Fi\' -B 1 | cut -d\')\' -f2')).stdout.trim();
+	const wifiAdaptor = 'Wi-Fi';
````
I'm not sure why you are getting wifiAdaptor as an additional variable?̊̈ The shell command is already grepping to find 'Wi-Fi'...

**Comment by pcr910303** [comment]
I was trying to open a PR, but 'point 2' made me hesitate. 
Could you please clarify?

**Comment by SadeghHayeri** [comment]
for 'point 2' I use that command to grep true wifi name!
the name of the wifiAdaptor is by default 'Wi-Fi', but the users may have changed the name.
for example see my adaptor:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/9386624/58366161-807f1980-7ee3-11e9-8d74-2085dafe0893.png">

**Comment by pcr910303** [comment]
@SadeghHayeri Thinking more about point 2, the code currently doesn’t cover Ethernet-based Internet connections, Bluetooth-based ones, etc...
It looks like displaying a message asking the user to add the proxy server would be better... (Currently there is no such message or mention in README; That’s why I initially thought that the CLI should automatically register the proxy server...)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SadeghHayeri** [comment]
yeah, you are right, I didn't think about it.
i'll try to improve it, if I find time.
thanks @pcr910303

**Comment by pcr910303** [comment]
@SadeghHayeri This is something super off-topic, but I see you're connecting to a MSCHAPv2 EAP-PEAP network with macOS Mojave. 
As I have upgraded to Mojave, found out our school wifi doesn't connect (with a message 'Can't connect to wifi. Contact the IT administrator'), and downgraded to High Sierra multiple times, (about ~5 times) I'm very interested how you managed connect to the wifi.
Did the wifi connect without any problems?̊̈

**Comment by SadeghHayeri** [comment]
Yes my wifi connect very easy and with no problem.
I only select ssid in the list and submit my user/pass and connected!

<img width="562" alt="image" src="https://user-images.githubusercontent.com/9386624/58380022-e42b4480-7fc0-11e9-909e-0e71971b3639.png">

**Comment by pcr910303** [comment]
@SadeghHayeri Thanks!

**Comment by pcr910303** [comment]
@SadeghHayeri Okay, I'm trying to mitigate this issue, and I realized that the reason it works in your computer is that your Wi-Fi network service name isn't `Wi-Fi`, while the default is `Wi-Fi`, making the grep returning the wrong place.

Looks like instead of grepping `Wi-Fi`, grepping the current used network interface name (`en0`, `en1`, etc...) retrieved by a `route -n get 0.0.0.0` would be a more robust solution. (I'll not work for people who set the network adaptor name as `en*` thou...)

So the diff would more look like something like this...

```diff
// src/utils/system-proxy.js#L16 and #L22
-	const wifiAdaptor = (await exec('networksetup -listnetworkserviceorder | grep \'Wi-Fi\' -B 1 | cut -d\')\' -f2')).stdout.trim();
+	const wifiAdaptor = (await exec(`sh -c "networksetup -listnetworkserviceorder | grep \`route -n get 0.0.0.0 | grep 'interface' | cut -d ':' -f2\` -B 1 | head -n 1 | cut -d ' ' -f2"`)).stdout.trim();
```
