### ISSUE TITLE
Partitaly not working in South Korea

### ISSUE THREAD

**Issue by SalaryTheft** [SadeghHayeri/GreenTunnel#156]
**Describe the bug**
Green Tunnel partitaly not working in South Korea.

1. Green Tunnel installed on Docker container (under ESXi VM)
- HTTP : 301 Redirected to censorshiped webpage
- HTTPS :  green-tunnel:https-handler [HTTPS ERROR] server error Error: read ECONNRESET +265ms

2. Green Tunnel installed in VPS instance (Snap package)
- HTTP :  301 Redirected to censorshiped webpage
- HTTPS : works👍

3. Green Tunnel installed in Raspberry Pi (Snap package)
- Results are same with docker image

**Desktop (please complete the following information):**
Tested on macOS and Windows 11 with Firefox.

**Comment by Drugoy** [comment]
Docker version running locally (why would you even use GT if you have a VPS instance (expectedly abroad?)?), same result.

**Comment by ybshin5657** [comment]
> Docker version running locally (why would you even use GT if you have a VPS instance (expectedly abroad?)?) on linux, different country, same result.

Some websites do not allow access from well-known VPS IP addresses.
And because proxy traffics are not encrypted, it will be still blocked even if I use VPS provider from different country.

**Comment by Taewan-P** [comment]
Same here. I am unable to access certain sites in South Korea even with the proxy on. I am willing to provide a VPN account which is using the same ISP that produces this issue to the maintainers if they look into this..

**Comment by Drugoy** [comment]
This project received 0 updates to its code base for the past year. Thus, it has now become abandonware.

**Comment by Taewan-P** [comment]
😞
