### ISSUE TITLE
GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by nullalloc** [SadeghHayeri/GreenTunnel#157]
Green tunnel does not launch, neither from cli or gui, cli gives this error:
[3919257:0722/180911.448140:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
OS:pop!_os

**Comment by yazux** [comment]
hi, same problem on ubuntu 22.04.1, GNOME 42.4

**Comment by silentninja** [comment]
Launch the app using `green-tunnel --no-sandbox` from your terminal

**Comment by nullalloc** [comment]
Fixed by running the command provided by slientninja `green-tunnel --no-sandbox`
