### ISSUE TITLE
[macOS] A JavaScript error occured...

### ISSUE THREAD

**Issue by B4TT3RY** [SadeghHayeri/GreenTunnel#16]
**Describe the bug**
Just using browser, showing error.

**To Reproduce**
1. Using Browser
2. Error

**Screenshots**
<img width="422" alt="스크린샷 2019-06-02 오전 1 02 41" src="https://user-images.githubusercontent.com/12368101/58756441-a2a41780-8533-11e9-8569-b671289d810b.png">
<img width="422" alt="스크린샷 2019-06-02 오전 1 06 04" src="https://user-images.githubusercontent.com/12368101/58756442-a46ddb00-8533-11e9-808a-4a25abdc270c.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Browser: Safari, Chrome

**Comment by SadeghHayeri** [comment]
Fixed in v1.6.12
thanks for your report.
