### ISSUE TITLE
We Need Supported Version for Android Mobile.

### ISSUE THREAD

**Issue by mhaney3931** [SadeghHayeri/GreenTunnel#19]
Hi there,

it will be so great if we have mobile supported version for android.

Thank you

**Comment by SadeghHayeri** [comment]
I think it can't fit on this project.
thanks.

**Comment by Chidhambararajan** [comment]
Try running it in termux with npm and use the proxy with some android browser which supports proxy like the "privacy browser" in fdroid .
It worked for me!!
