### ISSUE TITLE
Squirrel fails to run (install) on virtual machine

### ISSUE THREAD

**Issue by Setaran** [SadeghHayeri/GreenTunnel#24]
**Describe the bug**
I downloaded green-tunnel, double clicked it, Squirrel.exe returned error:
This application could not be started. Do you want to view information about this issue?
Clicking yes opens this link:
https://docs.microsoft.com/en-us/dotnet/framework/deployment/initialization-errors-managing-the-user-experience?version=(null)&processName=Squirrel.exe&platform=0009&osver=6&isServer=0&shimver=4.0.30319.0

Green-tunnel eventually runs and a shortcut is created on the desktop but it doesn't circumvent websites like youtube so it doesn't work.
![2](https://user-images.githubusercontent.com/35542834/60867462-24c4e180-a240-11e9-8b31-e773881b4959.PNG)

In "Turn windows features on or off" I Installed ".NET Framework 3.5 (includes .NET 2.5 and 3.0)"
I also have .NET Framework 4.7 Advanced Services.

![1](https://user-images.githubusercontent.com/35542834/60867482-30b0a380-a240-11e9-9030-50c922a1c418.PNG)

I get the error twice on one run,
I can't install apps on the computer I'm using so I want to use green-tunnel on a virtual machine.

**To Reproduce**
Install the green-tunnel on a virtual machine.

**Expected behavior**
To not receive the error and for green-tunnel to actually work because it doesn't work.

**Desktop (please complete the following information):**
 - OS: Windows 10 1709 LTS 64-bit, VMWare 14.1.2
 - Browser : Chrome
 - Version :Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by Setaran** [comment]
I was checking other issues and found this one: https://github.com/SadeghHayeri/GreenTunnel/issues/23
Seems like green-tunnel is not setting the proxy automatically for me, when I checked, there was not proxy address implemented, I added 127.0.0.1 port 8000 and youtube opens up :D
But I'm using the latest version of green-tunnel (1.3.2)..

**Comment by Setaran** [comment]
Now, browser doesn't open anything and I got this error:
![3](https://user-images.githubusercontent.com/35542834/60868171-b8e37880-a241-11e9-9263-e0af4737889b.PNG)

**Comment by kamalhm** [comment]
I also got this error

**Comment by SadeghHayeri** [comment]
The squirrel bug should be resolved in v1.6.7.
I'm working on GUI error alerts to resolve second issue.
thanks.
