### ISSUE TITLE
SNI Routing with Passthrough instead of CONNECT Proxy

### ISSUE THREAD

**Issue by heri16** [SadeghHayeri/GreenTunnel#3]
**Is your feature request related to a problem?**

Some apps like Netflix do not support forward proxy even if it is set on the system-level.

**Describe the solution you'd like**

Implement DNS cloaking to 127.0.0.1:443 and use the SNI handshake to determine the endpoint to proxy towards at the backend.

**Describe alternatives you've considered**

Current alternative solution uses a SNI-capable reverse proxy with dnscrypt-proxy. See: https://gist.github.com/heri16/1c744d4603db107b5e26fc2b167b9676

Mobile os like android or iOS just needs to set their dns resolvers to the ipaddress of the host running GreenTunnel.

**Additional context**

There should be a way to do this without resorting to faking netflix certificates. It is commonly called SNI-Routing.

See: https://github.com/dlundquist/sniproxy

See: https://fabiolb.net/feature/tcp-sni-proxy/

See: https://proxy.dockerflow.com/sni-routing/

See: https://docs.traefik.io/v2.0/routing/routers/#configuring-tcp-routers

See: https://github.com/heptio/contour/pull/850

**Comment by 3140** [comment]
As a (unix only) workaround you can combine this proxy with [sniproxy](https://github.com/dlundquist/sniproxy) + [proxychains](https://github.com/haad/proxychains)

- Run GreenTunnel on a port (ex: 2020)
- Configure proxyChains to use GreenTunnel
- Run sniProxy with proxyChains

**Comment by Mahdi321** [comment]
> As a (unix only) workaround you can combine this proxy with [sniproxy](https://github.com/dlundquist/sniproxy) + [proxychains](https://github.com/haad/proxychains)
> 
>     * Run GreenTunnel on a port (ex: 2020)
> 
>     * Configure proxyChains to use GreenTunnel
> 
>     * Run sniProxy with proxyChains

What `sniproxy.conf` should be used. No proxifying happens here
```
$ sudo proxychains sniproxy -f -c '/home/m/Downloads/sniproxy-master/overlay/sniproxy.conf' 
ProxyChains-3.1 (http://proxychains.sf.net)
2019-07-06 06:10:10 [::ffff:127.0.0.1]:40732 -> [::ffff:127.0.1.1]:80 -> NONE [m-ThinkPad-E560] 113/113 bytes tx 133/266 bytes rx 0.000 seconds
2019-07-06 06:11:10 [::ffff:127.0.0.1]:40754 -> [::ffff:127.0.1.1]:80 -> NONE [m-ThinkPad-E560] 113/113 bytes tx 133/266 bytes rx 0.000 seconds
```
[sniproxy.conf.txt](https://github.com/SadeghHayeri/GreenTunnel/files/3364283/sniproxy.conf.txt)

[proxychains.conf.txt](https://github.com/SadeghHayeri/GreenTunnel/files/3364285/proxychains.conf.txt)

**Comment by Mahdi321** [comment]
> As a (unix only) workaround you can combine this proxy with [sniproxy](https://github.com/dlundquist/sniproxy) + [proxychains](https://github.com/haad/proxychains)
> 
>     * Run GreenTunnel on a port (ex: 2020)
> 
>     * Configure proxyChains to use GreenTunnel
> 
>     * Run sniProxy with proxyChains

What `sniproxy.conf` should be used. No proxifying happens here
```
$ sudo proxychains sniproxy -f -c '/home/m/Downloads/sniproxy-master/overlay/sniproxy.conf' 
ProxyChains-3.1 (http://proxychains.sf.net)
```
[sniproxy.conf.txt](https://github.com/SadeghHayeri/GreenTunnel/files/3364370/sniproxy.conf.txt)
