### ISSUE TITLE
Running green tunnel on android

### ISSUE THREAD

**Issue by KebabLord** [SadeghHayeri/GreenTunnel#31]
**Describe the bug**
Having problems with running green tunnel on my android phone's linux emulator

**To Reproduce**
1. I changed std_env with custom strings, otherwise it's prompting "unknown os: android" error
2. Installed all dependencies and runned green tunnel via terminal
3. Green tunnel screen came problemless
4. But i still can't connect to any blocked website

**Expected behavior**
Is there a better way to test green tunnel or debug it? In Dns crypt we were prerouting the dns to localhost, can we do the same in green tunnel? Is there an alternative way to use green tunnel on android?

**Smartphone (please complete the following information):**
 - Device: Samsung J4 Core
 - OS: Android
 - Browser: Firefox
 - Version: Oreo Go edition

**Comment by Chidhambararajan** [comment]
Try running it in termux with npm and use the proxy with some android browser which supports proxy like the "privacy browser" in fdroid .
It worked for me!!
