### ISSUE TITLE
GreenTunnel as a system service

### ISSUE THREAD

**Issue by ibnuh** [SadeghHayeri/GreenTunnel#34]
Opening terminal and doing the same thing everytime I want to bypass DPI just boring and repetitive. It would be nice if we can install GreenTunnel as a system service. 

Like something [dnscrypt-proxt](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-macOS#step-5---install-dnscrypt-proxy-as-a-system-service) provide.

**Comment by pcr910303** [comment]
@ibnuh Well, I didn’t check, but it just looks like a wrapper around [macOS launchd](https://en.m.wikipedia.org/wiki/Launchd).
You should be able to write your own service file and register using [launchctl](https://ss64.com/osx/launchctl.html).

Maybe [this](
https://alvinalexander.com/mac-os-x/launchd-examples-launchd-plist-file-examples-mac) might help.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by biblia19** [comment]
@ibnuh Hey, if you have a systemd check my code

`/etc/systemd/system/green-tunnel.service`

```
[Unit]
Description=GreenTunnel bypasses DPI (Deep Packet Inspection) systems
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/gt --port (any port you want)
TimeoutSec=15
Restart=always

[Install]
WantedBy=multi-user.target
```

And autostart on boot
```
systemctl enable green-tunnel
systemctl start green-tunnel
```
