### ISSUE TITLE
Green Tunnel doesn't work with Telecommunication Company of Iran(Mokhaberat)

### ISSUE THREAD

**Issue by mrmmg** [SadeghHayeri/GreenTunnel#35]
**Describe the bug**
1. Green Tunnel **doesn't work with Telecommunication Company of Iran(Mokhaberat)**. for example, youtube.com does not load at all! **can you solve this**?

2. When I open the .exe file I see an error(see Screenshots section for more information).

**Screenshots**
![green-tunnel-issue](https://user-images.githubusercontent.com/30490118/65835499-cdd92080-e2f3-11e9-893d-d30d6d027e6d.jpg)
when i click on yes button, this [page](https://docs.microsoft.com/en-us/dotnet/framework/deployment/initialization-errors-managing-the-user-experience?version=(null)&processName=Squirrel.exe&platform=0009&osver=7&isServer=0&shimver=4.0.30319.0) is load

**Desktop (please complete the following information):**
 - OS: windows 10 - 64bit
- OS Build: 18362.387
 - Browser: Chrome
 - Version: 77

**Comment by SadeghHayeri** [comment]
Resolve in v1.6.7
