### ISSUE TITLE
Don't send spam mail

### ISSUE THREAD

**Issue by rinukkusu** [SadeghHayeri/GreenTunnel#4]
You're sending out spam mail to (probably?) crawled mail addresses from GitHub profiles. This is not okay. I've reported you to MailChimp and on GitHub.

**Comment by SadeghHayeri** [comment]
I only send 100 mail to most efficient profiles (top 100) how like GoodbyDPI to invite them to test my app and help to fix bugs. this is not a spam man :/

**Comment by rinukkusu** [comment]
It is spam if it's advertising for which I didn't sign up :P
