### ISSUE TITLE
Any config changed? from 1.52 to 1.60

### ISSUE THREAD

**Issue by jasonliul** [SadeghHayeri/GreenTunnel#47]
i've used 1.52 windows for a while, set browser proxy http/https:8000, it works just fine.
now install 1.62, doesn't work anyway, maybe some config setting changed?

**Comment by SadeghHayeri** [comment]
Sorry, I change default port to 5000 for a test. It will return to 8000 in next release.
Thanks.

**Comment by SadeghHayeri** [comment]
Also in last version (v1.6.7) it should set global system-proxy automatically.

**Comment by jasonliul** [comment]
Thank for reply so quick, but auto set proxy is not help for Firefox user. :)

**Comment by jasonliul** [comment]
For windows user, set default port 8000 is the best way, more simple, more easy.

**Comment by SadeghHayeri** [comment]
In Firefox select ‘use system proxy settings’ option in proxy settings and it should work.

**Comment by SadeghHayeri** [comment]
In Firefox select ‘use system proxy settings’ option in proxy settings and it should work.

**Comment by jasonliul** [comment]
Ok, i've tried, still doesn't work. there're no proxy setting in my IE.
Thanks anyway.

**Comment by SadeghHayeri** [comment]
no, go to `Firefox -> preferences -> General -> Network Settings` and check `Use system proxy settings`.

also check [FoxyProxy](https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/), [SwitchyOmega](https://addons.mozilla.org/en-US/firefox/addon/switchyomega/) extentions for Firefox.

**Comment by jasonliul** [comment]
Thanks, 1.69 now works like a charm.
but something stranger, i use GT watching youtube, and 1.52 works better than 1.69.

**Comment by jasonliul** [comment]
Thanks, 1.69 now works like a charm.

**Comment by jasonliul** [comment]
i've test the download speed, 1.69 higher than 1.52, nice job, sir.
