### ISSUE TITLE
Crash on Windows 10

### ISSUE THREAD

**Issue by VSG24** [SadeghHayeri/GreenTunnel#5]
![Capture](https://user-images.githubusercontent.com/7500363/55665083-45029000-584e-11e9-85e7-e609299e7dc2.PNG)

**Comment by meness** [comment]
I have not the chance yet to try your fork and hope you fix this issue soon.

**Comment by SadeghHayeri** [comment]
Sorry man :(
I can’ find why this happened. It alltime happened?
(+ in windows you must set your proxy settings on 127.0.0.1:8000)

I will try to fix it, thanks for your report 💙

**Comment by VSG24** [comment]
I'm pretty sure I set up the proxy settings correctly. Green Tunnel crashes every time it is launched. Even if you click on the OK button it crashes again until I force close it from Task Manager.

**Comment by VSG24** [comment]
I forgot to mention that `Squirrel.exe` crashes as well. Right after executing the release `exe` build.

**Comment by SadeghHayeri** [comment]
@VSG24 
javascript popup error fixed in v1.6.12.
also `Squirrel.exe` crash fixed in v1.5.0.
