### ISSUE TITLE
MacOS GUI JavaScript error

### ISSUE THREAD

**Issue by madmurdok** [SadeghHayeri/GreenTunnel#53]
**Describe the bug**
Appears on open the application. 

**To Reproduce**
1. Download latest release v1.6.11
2. Extract app from zip-arch
3. Move app to applications folder
4. Open App

**Expected behavior**
It should works without this error :)

**Screenshots**
![image](https://user-images.githubusercontent.com/23568909/72210813-0df29680-34d2-11ea-88f7-8c85143065d5.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6 
 - App Version 1.6.11

**Comment by willihangga** [comment]
get this error on MacOS Catalina 10.15.2 (19C57), app version v1.6.11
 
<img width="469" alt="Screen Shot 2020-01-25 at 22 00 48" src="https://user-images.githubusercontent.com/5728629/73123075-4e680f00-3fbe-11ea-96ba-d2c839e1105f.png">

**Comment by romariorobby** [comment]
What does zip-arch mean? and how to do that?

**Comment by madmurdok** [comment]
> What does zip-arch mean? and how to do that?

I got application via zip-file(green-tunnel-macos.zip) from releases section.

**Comment by romariorobby** [comment]
Oh I see. I did it, but still get this error. I try CLI it seems working now.

**Comment by SadeghHayeri** [comment]
@madmurdok @willihangga
I disable dialog messages completely in the new version, can you check it now?

**Comment by romariorobby** [comment]
@SadeghHayeri Yes, it's working fine now. Thanks for your response.
