### ISSUE TITLE
Is there any plan to release cli-only binaries?

### ISSUE THREAD

**Issue by incheon-kim** [SadeghHayeri/GreenTunnel#54]
I'm planning to use this project as child-process of my project to provide users uncensorship without affects any other applications. And it needed to be executable without any node.js installation. Actually, I tried to make one with pkg myself. But I am getting a bunch of Syntax Errors('import', 'export', '...').

Do you have any plans for it?

**Comment by AOTOA** [comment]
nexe works fine

https://github.com/nexe/nexe

**Comment by incheon-kim** [comment]
> nexe works fine
> 
> https://github.com/nexe/nexe

Could you share build arguments? Still getting error MODULE_NOT_FOUND when running compiled executable file.

**Comment by AOTOA** [comment]
Which platform?

**Comment by AOTOA** [comment]
@incheon-kim Which platform?

**Comment by incheon-kim** [comment]
> @incheon-kim Which platform?

I'm trying on macOS 10.15.3 Catalina. But all three built Windows/Mac/Linux binaries not working with same error.
I installed all dependencies and make source codes included before compile with nexe.
If I move compiled binaries at the root of cloned repository directory that contains source codes, it works. I don't know what is going on.
