### ISSUE TITLE
Issue with Chrome extension: SwitchyOmega

### ISSUE THREAD

**Issue by gvmohzibat** [SadeghHayeri/GreenTunnel#55]
**Describe the bug**
When [SwitchyOmega](https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif) is enabled in Chrome/Chromium, GreenTunnel doesn't work. Neither `[direct]` nor `[System Proxy]` works. Disabling the extension solves the problem immediately.

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Browser Chrome or Chromium
 - Version 80

**Comment by SadeghHayeri** [comment]
Hi Vahid Jaan, 
I test it with chrome version of this extension and it works perfect, I think your issue is related to SwitchOmega.
can you check GT logs to see if any unusual log is there? (use -v '*' option)
