### ISSUE TITLE
Integration with Pi-Hole

### ISSUE THREAD

**Issue by ignatiusmb** [SadeghHayeri/GreenTunnel#57]
**Is your feature request related to a problem? Please describe.**
How would you go about setting this up as network-wide service instead of per device. 

**Describe the solution you'd like**
Currently Pi-Hole acts as my DNS server and all requests goes through it with DoH too. So, all devices in my home network receives the benefit inherently. Maybe, there's a way to integrate it with Pi-Hole?

**Describe alternatives you've considered**
Perhaps GreenTunnel could act as a server too like Pi-Hole but it negates the benefits of Pi-Hole ad-blocking.

**Comment by SadeghHayeri** [comment]
Run GreenTunnel with `--dns-server` flag on your server (maybe run both gt and pi-hole on the same server)
`gt --dns-server <your DoH server adddress> --ip 0.0.0.0 --port 8000`
open port 8000 of server and now all your HTTP and HTTPS traffic go through green-tunnel and pi-hole.
