### ISSUE TITLE
GT crushes when visiting some sites

### ISSUE THREAD

**Issue by mFoxRU** [SadeghHayeri/GreenTunnel#6]
**Describe the bug**
GT crushes when visiting some sites

**To Reproduce**
Sorry, can't provide URL as it contains sensitive data

**Expected behavior**
GT doesn't crush

**Screenshots**
![image](https://user-images.githubusercontent.com/5925970/56235662-80902c00-6090-11e9-8865-64ed1f5aaf1a.png)

**Desktop (please complete the following information):**
 - OS: Win7 x64
 - Browser: Firefox
 - Version: 67.0b9

**Additional context**
I'll add sites that reproduce this error when i find more

**Comment by mFoxRU** [comment]
https://tgstat.ru/research
![image](https://user-images.githubusercontent.com/5925970/56276651-90992180-610b-11e9-83bb-f52ace5ec123.png)

**Comment by 3140** [comment]
Should be fully resolved by #9
