### ISSUE TITLE
Docker image and ARMv7 on Raspberry Pi

### ISSUE THREAD

**Issue by chung1905** [SadeghHayeri/GreenTunnel#61]
**Describe the bug**
Can't start application via Docker on Raspbian 18.04.

**To Reproduce**
1. Run `docker run -p 8000:8000 sadeghhayeri/green-tunnel`
2. See error:
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Expected behavior**
Application starts

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Raspbian
 - Version 18.04

**Comment by albadrun** [comment]
Every tag on Docker Hub is specialized to `linux/amd64` arch. For `arm` arch, you can build the docker image yourself. :D

**Comment by ardinusawan** [comment]
Hi @chung1905, I create PR for this case. You can give it a try here: https://github.com/SadeghHayeri/GreenTunnel/pull/68

**Comment by RaminMT** [comment]
If you noticed in the readme you should use `arm` tag: `sadeghhayeri/green-tunnel:arm`
I myself installed nodejs using nodesource and installed it through npm

**Comment by chung1905** [comment]
Thank @ardinusawan , it works on my side.

Closing issue.
