### ISSUE TITLE
HTTP website doesn't work great on vbulletin forum

### ISSUE THREAD

**Issue by mohammadrnv** [SadeghHayeri/GreenTunnel#64]
Apologizing to other. English is not my native language.Sorry about this

سلام داداش امیدوارم که حالت خوب باشه
یه مشکلی که هست تو فروم ها اکثریتشون مشکل دارن 
فک کنم بخاطر http باید باشه که پکت هارو قسمت قسمت میکنه داره 
نمونه اشو هم برات شات گذاشتم 
به عنوان مثال

![Annotation 2020-04-16 215249](https://user-images.githubusercontent.com/51803572/79486897-a5650980-802c-11ea-8dcd-4467eac0eff8.jpg)

دستوری نداره http ؟تقسیم نکنه

**Comment by SadeghHayeri** [comment]
سلام عزیز
طبق استاندارد باید درست کار کنه روی همه‌ی سرورها، ولی خب امکان داره یه تنظیمات خاصی روی وب‌سرور این سایت‌ها باشه که مشکل ایجاد بشه.
نه خودش که دستوری نداره که وایت‌لیست بلک‌لیست ایجاد کنه هنوز (اگه وقت کنم می‌خوام اضافه کنم) ولی الان می‌تونی از افزونه‌ی omega proxy استفاده کنی
میتونی توش تعریف کنی که مثلا p30download رو از توی گرین‌تانل رد نکنه.
موفق باشی
