### ISSUE TITLE
Share Bypassed Connection over Ethernet

### ISSUE THREAD

**Issue by hadyanq1** [SadeghHayeri/GreenTunnel#67]
Hi, thank you for this project, Green Tunnel works great in my case of bypassing my ISP block over Netflix. I do however have one issue or feature request, is it possible to share the connection to other device?

My plan is to run Green Tunnel on my Ubuntu machine, and then share the connection over LAN, so that other devices can also use the bypass without actually having to run Green Tunnel itself. I intend to access Netflix from other devices such as smart TV, phones or other PCs.

So far I have tried to set up my LAN to share the internet, the internet works and I can browse from other device, but it still can't access Netflix. Can you point out what I may have missed?

Thank you.

**Comment by SadeghHayeri** [comment]
Hi,
You can run gt with `--ip 0.0.0.0` to listen on all interfaces (default is localhost) and connect it from other devices. But if you set up it on your TV, Netflix app finds that you use proxy and block it (through android APIs).
I use WARP VPN on my raspberry pi and set up it as a gateway to send all of the traffic over the VPN and its work grate for Netflix.

**Comment by SP4RKiOP** [comment]
i did the same also configured the iptables :- 
sudo iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 80 -j REDIRECT --to-port 8000
sudo iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 443 -j REDIRECT --to-port 8000

eth1 is my usb to ethernet adapter which connected to a router for wifi and lan ports (all bypassed dpi).

but still eth1 traffic is not redirected to port 8000, can you help me please?
