### ISSUE TITLE
Doesn't work in Turkey.

### ISSUE THREAD

**Issue by aqaq55aq** [SadeghHayeri/GreenTunnel#8]
Hello, it doesn't work with Turkish ISPs. I am currently using goodbyedpi with dnscrypt but even that doesn't work here. I contacted with the creator of goodbyedpi "ValdikSS" he told me that TurkTelekom ISP's DPI can detect obfuscated traffic, but he will work to implement a new setting for Turkish users. Then I saw your project, it looks good but not working in Turkey with blocked websites like  "wikipedia.org - imgur.com". I, personally, and people in Turkey will be very appreciated if you can make it work here. Thank you so much! Have a nice day.

**Comment by KebabLord** [comment]
green tunnel is working fine with turk.net.
