### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by m-koushan** [SadeghHayeri/GreenTunnel#83]
how can i completely uninstall green tunnel? 
it made so many problems for my network

**Comment by dostarora97** [comment]
@SadeghHayeri  After uninstalling from the network stops working
Windows 10 Version 10.0.19041 Build 19041
GreenTunnel v1.7.4

**Comment by SeldRiyo** [comment]
> @SadeghHayeri After uninstalling from the network stops working
> Windows 10 Version 10.0.19041 Build 19041
> GreenTunnel v1.7.4
repair your registry  with third party apps, it should fix that

**Comment by dostarora97** [comment]
Yeah well, I [opened an issue](https://github.com/SadeghHayeri/GreenTunnel/issues/84), describing the method that I tried. Basically I had to manually delete few registries, and got my internet back to work normally.

**Comment by vnbubba** [comment]
How to uninstall it on Ubuntu? I use CLI
