### ISSUE TITLE
Termux integration with Green Tunnel to run it on android

### ISSUE THREAD

**Issue by hasanparasteh** [SadeghHayeri/GreenTunnel#94]
There's no android release of Green Tunnel، so it came to my mind that if there's a npm package then I can use it under termux and set proxy to connect.

but green tunnel won't work properly...here is the commands that I used to install in Android 10 termux are:

```
pkg install nodejs
npm i -g green-tunnel
```

node & npm version was:
```
~ $ node -v                                            
v14.15.4
~ $ npm -v                                              
6.14.10
```

**Comment by Chidhambararajan** [comment]
I am running green-tunnel on Android for a long time , I guess I cloned the src code in termux and then performed the installation operation.
Green-Tunnel is completely written in JS , so green-tunnel wouldn't need platform specifi builds

**Comment by hasanparasteh** [comment]
I installed it via the npm package manager. So let me try cloning the repo...

**Comment by hasanparasteh** [comment]
it fixed
